Linkurious/linkurious-rest-client

- .ciconfig
- index.ts
- src/LinkuriousError.ts
- src/errorListener/index.ts
- src/http/fetcher.ts
- src/index.ts
- src/module/AdminModule.ts
- src/module/AlertModule.ts
- src/module/EdgeModule.ts
- src/module/GraphModule.ts
- src/module/Module.ts
- src/module/MyModule.ts
- src/module/NodeModule.ts
- src/module/SearchModule.ts
- src/module/VisualizationModule.ts
- src/module/VisualizationParser.ts
- src/response/errors.ts
- src/response/success.ts
- src/transformer/index.ts
- test/fetcher_spec.ts
- test/index_spec.ts
- tsconfig.json
Finally what has been done : 
- add the transformer and listener to the rest-client
- add a method `request` in `modules/module` that handle response transformation and dispatching error events
- I only touched new API
Because, changing all API responses represent too much work in LKE, It can cause many regression and it will be really difficult too validate (some features had too much edge cases to be sure at 100% that everything works fine).
Only new APIs will use this new strategy of (transformer + listener), old ones will still work has before until we refactor them.
Only new APIs needs to be validated. It will be a bit harder too maintain but we limit regressions and possibly critical bugs.
> API refactoring

- package-lock.json
- src/module/AdminModule.ts
- src/module/AlertModule.ts
The backend it still not ready.
> add the new api calls for the alert folder

- .eslintrc.js
- README.md
- index.ts
- src/index.ts
- src/models/AccessRights.ts
- src/models/DataSource.ts
- src/models/Schema.ts
- src/module/AccessRightsModule.ts
- src/module/AdminModule.ts
- src/module/SchemaModule.ts
- src/response/errors.ts
> Property Key Access Rights

- src/api/Search/index.ts
- src/api/Search/types.ts
- src/http/response.ts
EPIC: https://github.com/Linkurious/linkurious-server/issues/1359
Issue: https://github.com/Linkurious/linkurious-rest-client/issues/131
> Search Syntax

- src/api/Search/index.ts
- src/api/Search/types.ts
EPIC: Linkurious/linkurious-server#1359
Issue: #131
> Advanced search syntax

- src/api/CustomAction/types.ts
Issue: https://github.com/Linkurious/linkurious-shared/issues/65
> Add incompatible-restrictions

- src/api/User/index.ts
> Add missing errorKey

- src/api/DataSource/index.ts
> #138 auto set current source

- package-lock.json
- src/api/Auth/types.ts
- src/api/Config/types.ts
- src/api/DataSource/types.ts
- src/api/User/types.ts
- src/api/Visualization/types.ts
- src/api/displayTypes.ts
- src/api/graphItemTypes.ts
Updated interface names on rest client
> Lke 62 refactor api routes

- src/api/Config/types.ts
Jira issue: https://linkurious.atlassian.net/browse/LKE-837
> Add incremental indexation to RC

- src/api/Config/types.ts
Added parameter to rest-client for maxConnectionTimeout
> LKE-418-Standart-connection-timeout

- src/http/response.ts
dependency of https://github.com/Linkurious/linkurious-server/pull/2549
> LLKE-2352 config expansion

- src/api/Linkurious/index.ts
Jira ticket: https://linkurious.atlassian.net/browse/LKE-2749
> LKE-2749: rename analytics API url

- src/api/Alert/index.ts
- src/api/Alert/types.ts
- src/api/Config/types.ts
- src/api/DataSource/types.ts
- src/api/Linkurious/index.ts
- src/api/Visualization/types.ts
Jira ticket: https://linkurious.atlassian.net/browse/LKE-2510
Epic: https://linkurious.atlassian.net/browse/LKE-2370
> LKE-2510 rename match to case

- src/api/Alert/index.ts
- src/api/Alert/types.ts
- src/api/graphItemTypes.ts
JIRA
https://linkurious.atlassian.net/browse/LKE-2528
> LKE-2528 Save the state of a case

- src/api/Alert/index.ts
- src/api/Alert/types.ts
**DO NOT MERGE**
PR blocked by https://github.com/Linkurious/linkurious-rest-client/pull/221
**NOW READY MERGE**
> LKE-2023-Disallow-reopening-cases

- src/api/DataSource/types.ts
Jira: https://linkurious.atlassian.net/browse/LKE-3173
Server PR: https://github.com/Linkurious/linkurious-server/pull/2637
> LKE-3173 needIndex status

- package-lock.json
- src/api/Alert/types.ts
> LKE-3447-Add-in-progress-status-to-case-mgmt

- src/api/Alert/types.ts
- src/api/Visualization/types.ts
> LKE-3541-Fix-and-refactor-CM

- src/api/Alert/index.ts
- src/api/Alert/types.ts
Work in progress
**JIRA**  https://linkurious.atlassian.net/browse/LKE-3739
> Bulk Case assignment

- src/api/Alert/index.ts
- src/api/Alert/types.ts
Work in progress
**JIRA**  https://linkurious.atlassian.net/browse/LKE-3739
> LKE-3739 Eligible users list

- src/api/Alert/index.ts
- src/api/Alert/types.ts
This is a staging branch for the epic: **Manual Case Assignment**
**JIRA** https://linkurious.atlassian.net/browse/LKE-2930
> LKE-2930 EPIC: "Manual Case Assignment" [STAGE]

- src/api/GraphSchema/index.ts
Jira: https://linkurious.atlassian.net/browse/LKE-3877
> LKE-3877 Add ALREADY_EXISTS

- src/api/Alert/types.ts
* LKE-2932-Groups-for-Alerts
* Linted
* Revert removing group access-rights
* Added sourceKey to IBaseAlert
* Update types.ts
> Merge develop into develop-next [ci:run]

- src/api/Alert/index.ts
- src/api/Alert/types.ts
**JIRA** https://linkurious.atlassian.net/browse/LKE-4127?focusedCommentId=21588
> LKE-4127 Create an API to execute an alert

- src/api/DataSource/types.ts
- src/api/displayTypes.ts
https://linkurious.atlassian.net/browse/LKE-4395
> LKE-4395 Properties order

- src/api/Alert/types.ts
* LKE-3743-Assignment-history
* Update types.ts
* Update types.ts
* Lint
* Revert "LKE-4395 Properties order (#318)"
This reverts commit 5a92957db42b323daf78dcd7fca96452dfd69121.
* Revert "Revert "LKE-4395 Properties order (#318)""
This reverts commit 43dab67afed558cbd7c0e6072a099107cc75b7ad.
> Merge develop-stable into develop [ci:run]

- src/api/Auth/index.ts
- src/api/Auth/types.ts
- src/api/Config/types.ts
https://linkurious.atlassian.net/browse/LKE-5266
_As an Admin, I expect that only authorized users have access to my instance of LKE._
> LKE-5266: authentication required by default

- index.ts
- src/api/Auth/index.ts
- src/api/Auth/types.ts
- src/api/Config/types.ts
- src/api/License/index.ts
- src/api/License/types.ts
- src/http/response.ts
- src/index.ts
https://linkurious.atlassian.net/browse/LKE-5654
_As an admin, I expect to install LKE for the first time with a valid license_
> LKE-5654: Enforce license during installation

- src/api/displayTypes.ts
https://linkurious.atlassian.net/browse/LKE-5884
_As an admin I expect to be able to configure dynamic sizing with a log function._
> LKE-5884: Add logarithmic dynamic sizing configuration

- package.json
https://linkurious.atlassian.net/browse/LKE-6042
> LKE-6042: Remove "npm" from the "engines" section of the package.json

- src/api/User/types.ts
https://linkurious.atlassian.net/browse/LKE-7213
> LKE-7213: Type "action" as optional on GET /api/:sourceKey/groups

- src/api/spaces/index.ts
- src/api/spaces/types.ts
- src/index.ts
https://linkurious.atlassian.net/browse/LKE-7354
As a user who is a part of a group with the _Manage Spaces_ right, I expect to see :
* All spaces on the _Resources_ page
* Only spaces that are shared with my group on the _Space dashboard_
> LKE-7354: Refine space permissions

- src/api/Visualization/index.ts
- src/api/Visualization/types.ts
- src/api/spaces/index.ts
https://linkurious.atlassian.net/browse/LKE-7223
> LKE-7223: Manage visualizations within a space

- src/api/Config/types.ts
- src/api/Search/types.ts
https://linkurious.atlassian.net/browse/LKE-7470
> LKE-7470: Remove obsolete Neo4j v3.5 types

- src/api/commonTypes.ts
- src/api/spaces/index.ts
- src/api/spaces/types.ts
https://linkurious.atlassian.net/browse/LKE-7252
> LKE-7252: Add server-side pagination for spaces

- src/api/commonTypes.ts
- src/api/spaces/index.ts
https://linkurious.atlassian.net/browse/LKE-7252
Add a `totalCount` to the `getAllSpaces()` and `getSpacesSharedWithMe()` responses.
> LKE-7252: Add a "totalCount" to the getSpaces responses

- package-lock.json
- package.json
https://linkurious.atlassian.net/browse/LKE-7814
* This pull request updates typescript from 4.8.4 to 4.9.4.
* It also update the type definitions of express and superagent.
> LKE-7814: Update to Typescript 4.9.4

- src/api/Alert/types.ts
fixes: https://linkurious.atlassian.net/browse/LKE-7684
> LKE-7684 Replace GetCasesSortDirection with SortDirection

- src/api/Visualization/types.ts
fix: https://linkurious.atlassian.net/browse/LKE-8215
> LKE-8215 Add current editor info in the shared with me section

- src/api/Visualization/index.ts
fix: https://linkurious.atlassian.net/browse/LKE-8435
> LKE-8435: (fix) Add visualization locked to expected errors

- src/api/Config/types.ts
https://linkurious.atlassian.net/browse/LKE-7922
> LKE-7922: Add config for the Promotheus metrics endpoint

- src/api/AccessRight/types.ts
> LKE-9343 added a separate action for reading the graph schema as an admin

- package-lock.json
- package.json
- test/restClient.spec.ts
https://linkurious.atlassian.net/browse/LKE-9867
> LKE-9867: Remove dev dependency chai

- src/api/spaces/index.ts
- src/api/spaces/types.ts
https://linkurious.atlassian.net/browse/LKE-9667
> LKE-9667: Add the /spaces/tree resource

- package-lock.json
- package.json
https://linkurious.atlassian.net/browse/LKE-10019
Update mocha from 8.3.2 to 10.2.0.
> LKE-10019: Update mocha from 8.3.2 to 10.2.0

- index.ts
- src/api/GraphQuery/types.ts
- src/api/favorite/index.ts
- src/api/favorite/types.ts
- src/index.ts
https://linkurious.atlassian.net/browse/LKE-10160
> LKE-10160: Add the user favorite queries API

- src/api/DataSource/types.ts
https://linkurious.atlassian.net/browse/LKE-10423
> LKE-10423: Add support for native dates on Memgraph

- src/api/webhook/types.ts
* https://linkurious.atlassian.net/browse/LKE-10301
* This follows up https://github.com/Linkurious/linkurious-rest-client/pull/663
> LKE-10301: Complete the webhook events

- src/api/User/types.ts
https://linkurious.atlassian.net/browse/LKE-10720
> LKE-10720: Add UUIDs to groups

- src/api/Tag/types.ts
Reworking the interface for tags to include all data. We need the owner information for the delete (owner can delete). If we have a good reason to want to hide the 'uuid' field, tell me, I can add an Omit.
> LKE-11160 feat(query-tags): delete

- src/api/entityResolution/index.ts
- src/api/entityResolution/types.ts
https://linkurious.atlassian.net/browse/LKE-12011
> LKE-12011: Add the entity resolution mapping API

- src/api/Alert/types.ts
> LKE-12088 adding caseAttributesQueryDialect on alerts

- src/api/Config/types.ts
LKE-10541
https://github.com/Linkurious/linkurious-server/pull/4981
> LKE-10541 added db.allowFutureStoreVersion config flag

- src/api/entityResolution/index.ts
- src/api/entityResolution/types.ts
https://linkurious.atlassian.net/browse/LKE-11926
> LKE-11926: Finer grained entity resolution ingestion

- src/api/entityResolution/types.ts
https://linkurious.atlassian.net/browse/LKE-12435
> LKE-12435: Improve the ingestion status endpoint

- src/api/Config/types.ts
- src/api/entityResolution/types.ts
https://linkurious.atlassian.net/browse/LKE-12401
> LKE-12401: Entity Resolution - Map adjacent nodes

- src/api/GraphQuery/queryBuilder.ts
https://linkurious.atlassian.net/browse/LKE-12482
> LKE-12483: Add NULL and NOT NULL operators

- src/api/Config/types.ts
- src/api/entityResolution/index.ts
- src/api/entityResolution/types.ts
https://linkurious.atlassian.net/browse/LKE-12400
> LKE-12400: Merge full and incremental entity resolution ingestion

- src/api/entityResolution/index.ts
- src/api/entityResolution/types.ts
https://linkurious.atlassian.net/browse/LKE-12719
> LKE-12719: Expose entity resolution metrics

- src/api/entityResolution/types.ts
Add missing senzing attributes https://linkurious.atlassian.net/browse/LKE-12867
Group association attributes are available in senzing
https://senzing.zendesk.com/hc/en-us/article_attachments/38201367144595
Just add them as simple person attributes
https://github.com/Linkurious/linkurious-frontend/pull/6004
https://github.com/Linkurious/linkurious-rest-client/pull/798
https://github.com/Linkurious/linkurious-entity-resolution/pull/82
> LKE-12867 feat: add group association attributes

- src/api/entityResolution/types.ts
Add the resolved entities in order to not always in server and frontend rely on strings
> LKE-12945 feat(ER): Add resolved entities constants

- src/api/Config/types.ts
https://linkurious.atlassian.net/browse/LKE-13053
See also related server pull request https://github.com/Linkurious/linkurious-server/pull/5237
> LKE-13053: Remove the entityNodeCategories config

- src/api/Config/types.ts
**Jira Ticket:**
https://linkurious.atlassian.net/browse/LKE-13103
**Description:**
Add Cluster Config Types
> LKE-131013 feat(Active/Active): Add Cluster config types

- src/api/Config/types.ts
Jira Ref: https://linkurious.atlassian.net/browse/LKE-10504
> LKE-10504 feat: Active/Active cluster mode

- src/api/GraphQuery/queryCheckRun.ts
When the query timeout we want to send a partial response
> LKE-13326 feat(Query): add is partial in RunQueryResponse

- src/api/Config/types.ts
Add entityResolutionSourceKey config
> LKE-13380 feat(ER): Add ER source key config

- src/api/Config/types.ts
https://linkurious.atlassian.net/browse/LKE-13497
> LKE-13497: Disable custom groups

- src/api/Config/types.ts
https://linkurious.atlassian.net/browse/LKE-13495
> LKE-13495: Disable log report download

- src/api/Config/types.ts
- src/http/response.ts
https://linkurious.atlassian.net/browse/LKE-13320
> LKE-13320: Improve error handling

- src/api/GraphSchema/types.ts
https://linkurious.atlassian.net/browse/LKE-13852
> LKE-13852: Expose search support info

- src/api/DataSource/types.ts
https://linkurious.atlassian.net/browse/LKE-13903
> LKE-13903: Add the staticSchema data-source feature

- src/api/Alert/index.ts
- src/api/Alert/types.ts
https://linkurious.atlassian.net/browse/LKE-13959
> LKE-13959: Fix case column values search
